# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170512_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
