# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='deleted',
        ),
        migrations.AddField(
            model_name='listing',
            name='removed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
