# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20170512_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='tags',
        ),
    ]
