# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='logo',
            field=models.ImageField(upload_to='regions/logos'),
        ),
    ]
